CREATE TABLE IF NOT EXISTS sys_user (
    user_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
    dept_id BIGINT NOT NULL COMMENT '部门ID',
    user_name VARCHAR(64) NOT NULL COMMENT '用户账号',
    nick_name VARCHAR(64) NOT NULL COMMENT '用户昵称',
    email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    phonenumber VARCHAR(32) DEFAULT NULL COMMENT '手机号码',
    sex CHAR(1) DEFAULT '0' COMMENT '性别：0未知，1男，2女',
    password VARCHAR(100) NOT NULL COMMENT 'BCrypt密码',
    status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态：0正常，1停用',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_by VARCHAR(64) DEFAULT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(64) DEFAULT NULL,
    update_time DATETIME DEFAULT NULL,
    del_flag CHAR(1) NOT NULL DEFAULT '0',
    UNIQUE KEY uk_sys_user_name_normal (user_name, del_flag),
    KEY idx_sys_user_dept_status (dept_id, status, del_flag),
    KEY idx_sys_user_phone (phonenumber, del_flag),
    KEY idx_sys_user_email (email, del_flag)
) COMMENT='用户表';